### ISSUE TITLE
User Enumeration Vulnerability

### ISSUE THREAD

**Issue by justafriendofyours** [chartjes/opencfp#177]
I found your project when registering during a CFP.

The forgot password page (/forgot) has a [user enumeration vulnerability](https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_%28OWASP-AT-002%29).

If I type in an invalid username such as `notreal@example.com` I receive a message back indicating the following:
> Error: We couldn't find a user with that email

A valid e-mail account gives a distinctly different message:
>Success: An email giving you a link to reset your password has been sent.

*Theoretically* this can be scripted to enumerate all usernames stored in an opencfp system.

Additionally, if this is not throttled it could lead to both an denial of service attack as well as fill a mailbox of a registrant.

**Comment by chartjes** [comment]
So what is your suggestion for a better error message?

**Comment by jvoisin** [comment]
Maybe something like "If your email was valid, we sent a link to reset your password at $EMAIL_ADDRESS".

**Comment by chartjes** [comment]
I changed the error message, thanks for the feedback @jvoisin @justafriendofyours
